export const BAD_REQUEST_STATUS_CODE = 400
export const SUCCESS_STATUS_CODE = 200
export const SUCCESS_CREATE_STATUS_CODE = 201
export const ERROR_SERVER_STATUS_CODE = 500
export const NOT_FOUND_STATUS_CODE = 404
